import "@/styles/globals.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import gymlogo from "../public/gymlogo.webp";
import muscle from "../public/muscle.gif";
import { BiMenu } from "react-icons/bi";
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="z-10 p-4 flex justify-between items-center fixed top-0 left-0 w-[100%]">
        <div className="flex justify-center text-xl gap-x-2 items-center">
          <Image className="h-10 w-10" src={gymlogo} alt="gymlogo" />
          <h2 className="font-bold fon">Fit N Fine</h2>
        </div>
        <div className="group relative sm:hidden block">
          <button className="bg-gray-800 text-white px-6 h-10 rounded">
            <BiMenu />
          </button>
          <div
            tabindex="0"
            className="border-2 bg-black/[0.5] invisible border-gray-800 rounded w-24 absolute right-0 top-full transition-all opacity-0 group-hover:visible group-hover:opacity-100 group-hover:translate-y-1"
          >
            <ul className="py-1">
              <li>
                <Link href={"/"} className="block px-4 py-2 hover:bg-cyan-800">
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href={"/trainers"}
                  className="block px-4 py-2 hover:bg-cyan-800"
                >
                  Trainers
                </Link>
              </li>
              <li>
                <Link
                  href={"/schedule"}
                  className="block px-4 py-2 hover:bg-cyan-800"
                >
                  Schedule
                </Link>
              </li>
              <li>
                <Link
                  href={"/pricing"}
                  className="block px-4 py-2 hover:bg-cyan-800"
                >
                  Pricing
                </Link>
              </li>
              <li>
                <Link
                  href={"/about"}
                  className="block px-4 py-2 hover:bg-cyan-800"
                >
                  About
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="justify-between items-center md:gap-x-20 gap-x-10 sm:flex hidden">
          <ul className="flex md:gap-x-4 ">
            <Link href={"/"}>
              <li className="cursor-pointer p-2">Home</li>
            </Link>
            <Link href={"/trainers"}>
              <li className="cursor-pointer p-2">Trainers</li>
            </Link>
            <Link href={"/schedule"}>
              <li className="cursor-pointer p-2">Schedule</li>
            </Link>
            <Link href={"/pricing"}>
              <li className="cursor-pointer p-2">Pricing</li>
            </Link>
            <Link href={"/about"}>
              <li className="cursor-pointer p-2">About</li>
            </Link>
          </ul>
          <button className="bg-white text-orange-500 transform duration-300 hover:scale-105 p-2 flex group">
            Workout <Image src={muscle} width={22} height={22} alt="muscle" />
            <div className="absolute bottom-0  flex-col items-center hidden mb-6 group-hover:flex">
              <div className="w-3 h-3  rotate-45 bg-black"></div>
              <span className="relative z-10 p-2 text-xs leading-none text-white whitespace-no-wrap bg-black shadow-lg">
                A top aligned tooltip.
              </span>
            </div>
          </button>
        </div>
      </nav>
      <Component {...pageProps} />
    </>
  );
}
